CREATE TABLE casos (
	id SERIAL NOT NULL PRIMARY KEY,
    numero_de_caso NOT NULL VARCHAR(100),
	is_processed BOOLEAN DEFAULT FALSE,
	tipo_de_interesado NOT NULL VARCHAR(100),
    cliente NOT NULL VARCHAR(255),
    macrosegmento_nivel1_cliente VARCHAR(100),
    num_adherente_contrato VARCHAR(8),
    tipo_del_caso NOT NULL VARCHAR(12),
    estado_del_caso NOT NULL VARCHAR(12),
    tema2 NOT NULL VARCHAR(45),
    tema3 NOT NULL VARCHAR(60),
    tema4 NOT NULL VARCHAR(100),
    fecha_y_hora_creacion TIMESTAMPT NOT NULL,
    fecha_maxima_de_respuesta TIMESTAMPT NOT NULL,
    caso_a_nombre_de_tercero NOT NULL VARCHAR(2),
    autor NOT NULL VARCHAR(60),
    calidad_de_interesado NOT NULL VARCHAR(24),
    canal_preferido_de_respuesta NOT NULL VARCHAR(32),
    esta_desfasado NOT NULL VARCHAR(2),
    centro_de_trabajo VARCHAR(100),
    comuna VARCHAR(100),
    director_responsable_del_cliente NOT NULL VARCHAR(60),
    medio_de_respuesta VARCHAR(25),
    observaciones TEXT DEFAULT '',
    oficina_o_centro_de_atencion_salud VARCHAR(255),
    origen_de_la_presentacion NOT NULL VARCHAR(45),
    requiere_prorroga VARCHAR(2),
    sexo NOT NULL VARCHAR(10),
    via_de_respuesta VARCHAR(25),
    fecha_de_cierre DATE;
    fecha_de_respuesta NOT NULL VARCHAR(12),
    canal_de_recepcion NOT NULL VARCHAR(255),
    descripcion_de_la_presentacion TEXT DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);